# name: Deploy Node.js App

# on:
#   push:
#     branches:
#       - main

# jobs:
#   deploy:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v3

#       - name: Setup Node.js
#         uses: actions/setup-node@v3
#         with:
#           node-version: "20.x"

#       - name: Install dependencies
#         run: npm install

#       - name: Add SSH key
#         uses: webfactory/ssh-agent@v0.5.3
#         with:
#           ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

#       - name: Deploy to server
#         run: |
#           ssh -o StrictHostKeyChecking=no root@norbekovgroup.uz "
#             cd /var/www/course-server &&
#             git pull --rebase origin main &&
#             npm install &&
#             pm2 restart all &&
#             pm2 save
#           "
